---
# Specifies the location of the log file mysql sends logs to
LogFileLocation:
# Specifies the file where the startup manager will write its PID
PidFile:
Db:
  # Specifies the location of the script that starts and stops mysql using mysqld_safe and mysql.server
  DaemonPath:
  # Specifies the location of the script that performs the MySQL upgrade
  UpgradePath:
  # Specifies the user name for MySQL
  User: root
  # Specifies the password for connecting to MySQL
  Password:
Upgrader:
  # Specifies the location of the file containing the MySQL version as deployed
  PackageVersionFile:
  # Specifies the location of the file MySQL upgrade writes.
  LastUpgradedVersionFile:
Manager:
  # Specifies the location to store the statefile for MySQL boot
  StateFileLocation:
  # Specifies the job index of the MySQL node
  MyIP: 10.10.0.1
  # Comma-delimited list of IPs in the galera cluster
  ClusterIps: []
  # How many times to attempt database seeding before it fails
  MaxDatabaseSeedTries: 1
  ClusterProbeTimeout: 13
